title: Stealthstack Command Center
description: LCARS Homelab Dashboard

# LCARS Dark Theme
background:
  image: /images/lcars-bg.png
  opacity: 80
  blur: md
  brightness: 50

color: blue
theme: dark
headerStyle: boxed

quicklaunch:
  hideInternetSearch: false

language: en
background:
  image: /images/lcars-bg.png
  opacity: 80
  brightness: 60
