title: Stealthstack Command Center
description: LCARS Homelab Dashboard

background:
  image: /images/lcars-bg.png
  opacity: 80
  blur: md
  brightness: 60

color: blue
theme: dark
headerStyle: boxed

quicklaunch:
  hideInternetSearch: false

language: en
